name: "Grafana Cloud"
description: "Send metrics & logs to Grafana Cloud"
version: "0.2.0"
slug: "grafana_cloud"
init: false
arch:
  - amd64
  - aarch64
options:
  instance_name: homeassistant
  user_name: null
  access_token: null
  log_level: info
schema:
  user_name: str
  access_token: str
  instance_name: str?
  log_level: list(debug|info|warn|error)
homeassistant_api: true
map:
  - homeassistant_config
  - addon_config:rw
ports:
  80/tcp: null
ports_description:
  80/tcp: "Debug UI"
webui: "http://[HOST]:[PORT:80]/"
image: "ghcr.io/danielpanzella/hass-addon-grafana-cloud-{arch}"
